### ISSUE TITLE
I met a problem when run the example on ESP8266(Wemos D1 R1)

### ISSUE THREAD

**Issue by kaituozhe** [yourapiexpert/ATCommands#1]
In file included from D:\CProject\ArduinoProject\SerialRead_At\SerialRead_At.ino:13:
D:\CProject\ArduinoProject\libraries\ATCommands\src/ATCommands.h:91:20: error: extra qualification 'ATCommands::' on member 'hexToChar' [-fpermissive]
   91 |     static uint8_t ATCommands::hexToChar(const char ch);
      |                    ^~~~~~~~~~
exit status 1
为开发板 LOLIN(WeMos) D1 R1 编译时出错。

**Comment by berrak** [comment]
I have submitted a PR that solves this.

**Comment by 0x657373656C6C** [comment]
Fixed with #2
