### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by spiralbrain** [yourapiexpert/ATCommands#4]
This library does not seem to be working, I've tried everything. All AT commands just return Error. I am using the Arduino Nano

**Comment by 0x657373656C6C** [comment]
It works but if you provided sample code it would be more helpful.

I have been working on and off on version 2 of this library so I may finish that up over the weekend or early next week and release it. Since I am also testing that on a Nano you're welcome to try it.

**Comment by spiralbrain** [comment]
I am trying the example from the library. I wonder if I am doing something wrong here.
Will try on another ide as well. Thanks for your reply.

**Comment by spiralbrain** [comment]
Oh dear, my bad. I had made changes to the config files for the nano to allow larger buffer size. Works ok on another system.
